language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - ./test.sh
go_import_path: oauth2_proxy
sudo: false
notifications:
  email: false
